# Generated by Django 5.2.5 on 2025-08-29 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CdrData',
            fields=[
                ('phone_number', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('account_length', models.IntegerField()),
                ('vmail_message', models.IntegerField()),
                ('day_mins', models.FloatField()),
                ('day_calls', models.IntegerField()),
                ('day_charge', models.FloatField()),
                ('eve_mins', models.FloatField()),
                ('eve_calls', models.IntegerField()),
                ('eve_charge', models.FloatField()),
                ('night_mins', models.FloatField()),
                ('night_calls', models.IntegerField()),
                ('night_charge', models.FloatField()),
                ('intl_mins', models.FloatField()),
                ('intl_calls', models.IntegerField()),
                ('intl_charge', models.FloatField()),
                ('custserv_calls', models.IntegerField()),
                ('churn', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerSupportTicket',
            fields=[
                ('ticket_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_age', models.IntegerField()),
                ('customer_gender', models.CharField(max_length=50)),
                ('product_purchased', models.CharField(max_length=255)),
                ('date_of_purchase', models.DateField()),
                ('ticket_type', models.CharField(max_length=100)),
                ('ticket_subject', models.CharField(max_length=255)),
                ('ticket_description', models.TextField()),
                ('ticket_status', models.CharField(max_length=100)),
                ('resolution', models.TextField(blank=True, null=True)),
                ('ticket_priority', models.CharField(max_length=50)),
                ('ticket_channel', models.CharField(max_length=50)),
                ('first_response_time', models.DateTimeField(blank=True, null=True)),
                ('time_to_resolution', models.DateTimeField(blank=True, null=True)),
                ('customer_satisfaction_rating', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TelcoCustomerChurn',
            fields=[
                ('customerid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('gender', models.CharField(max_length=10)),
                ('seniorcitizen', models.IntegerField()),
                ('partner', models.CharField(max_length=10)),
                ('dependents', models.CharField(max_length=10)),
                ('tenure', models.IntegerField()),
                ('phoneservice', models.CharField(max_length=20)),
                ('multiplelines', models.CharField(max_length=50)),
                ('internetservice', models.CharField(max_length=50)),
                ('onlinesecurity', models.CharField(max_length=50)),
                ('onlinebackup', models.CharField(max_length=50)),
                ('deviceprotection', models.CharField(max_length=50)),
                ('techsupport', models.CharField(max_length=50)),
                ('streamingtv', models.CharField(max_length=50)),
                ('streamingmovies', models.CharField(max_length=50)),
                ('contract', models.CharField(max_length=50)),
                ('paperlessbilling', models.CharField(max_length=10)),
                ('paymentmethod', models.CharField(max_length=100)),
                ('monthlycharges', models.FloatField()),
                ('totalcharges', models.FloatField()),
                ('churn', models.CharField(max_length=10)),
            ],
        ),
    ]
