# Generated by Django 5.2.5 on 2025-08-30 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_finalout_alter_cdrdata_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cdrdata',
            table='cdr_data',
        ),
        migrations.AlterModelTable(
            name='customersupportticket',
            table='customer_support_ticket',
        ),
        migrations.AlterModelTable(
            name='telcocustomerchurn',
            table='telco_customer_churn',
        ),
    ]
